apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-run-git-mvn-buildah-kn-
  labels:
    tekton.dev/pipeline: pipeline-git-mvn-buildah-kn
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-git-mvn-buildah-kn
  workspaces: 
    - name: maven-settings
      configmap:
        name: maven-settings
    - name: source
      persistentVolumeClaim:
        claimName: a-place-to-hold-stuff
